前編のレビュー依頼
YYuanqi/e-navigator pull request #1
Opened 2018-10-16 11:00 UTC by YYuanqi

レビュー担当者　様

初めまして。　
前編を完成しましたので、レビューをお願い致します。
_________________________

#やりたかったこと
-登録機能の作成
-ログイン機能の作成
-プロファイル更新機能の作成

#やったこと
-上に書いてあるやりたかったこと
-入力値のフォーマットチェック
-bootstrapを利用したレイアウトの改善
-トップページの追加

#動作確認方法
以下のステップで動作確認を行ってください。

- [1]ホームページにアクセスする。
- [2] ホームページ中央の"Sign up now!"ボタンを押下し、登録画面に遷移する。
- [3] 登録フォームを記入して、"Create my account"ボタンを押下し、プロファイル画面に遷移する。
- [4]画面の右上の"Account"プールダウンボタンを押下し、"Log out"を選択し、ホームページに遷移する。
- [5]ホームページ右上の"Log in"ボタンを押下し、ログイン画面に遷移する。
- [6]ステップ[2]で使用した登録情報を入力し、中央の"Log in"ボタンを押下し、またプロファイル画面に遷移する。
- [7]右上の"Account"プールダウンボタンを押下し、"Setting"を選択し、プロファイル更新画面にアクセスする。
- [8]プロファイル更新画面で、"Date of birth"など任意の項目を編集し、"Save changes"ボタンを押下し、プロファイル画面に遷移する。
- [9]ステップ[8]で編集した内容は、プロファイル画面に表示される。

#何か分からない点や、ここ頑張りましたなどあればこちらに書いてください。
Ruby及びRailsには未経験ですが、この貴重なプログラムを完走したいと思います。
___________________
これから、よろしくお願いします

2018-10-18 07:41 UTC, pokotyamu commented
> https://github.com/YYuanqi/e-navigator/pull/1#issue-223205304

こちらのマークダウンが崩れているのが気になっています。
以下を参考に修正してみてください！
 [Markdown記法 サンプル集 - Qiita](https://qiita.com/tbpgr/items/989c6badefff69377da7)

書かれている内容としては、すごくいいと思います 👍

2018-10-18 07:45 UTC, pokotyamu commented
git/Github の使い方
---

プルリクエストのタイトルが『前編のレビュー依頼』、branch 名が、 editing になっていますね。
これだと、3ヶ月後に見た時に何をしてたんだろう？という風になると思います。
また、コミットメッセージも、 `bug fixes` だけだと、何のバグを直したの？という風になりませんか？ 😄 

以下を参考に、自分が思い返しやすい名前つけを心がけてほしいです。

- [【初心者向け】「コミットの粒度がわからない問題」の模範解答を考えてみた - Qiita](https://qiita.com/jnchito/items/40e0c7d32fde352607be)
- [How to write the perfect pull request | The GitHub Blog](https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/)

2018-10-18 07:45 UTC, pokotyamu commented
今回だったら

『ユーザーの登録/ログイン機能の実装』とかですかね 😄

2018-10-18 07:46 UTC, pokotyamu requested changes
@YYuanqi コメント付けました！いくつか質問している部分があるのでご確認よろしくおねがいします 🙏

2018-10-18 07:46 UTC, pokotyamu commented on Gemfile
> +  gem 'sqlite3', '1.3.13'
ローカルで sqlite を使っている理由ってありますか？ 🤔 
本番の DB と種類を分ける理由が知りたいです！

2018-10-18 07:46 UTC, pokotyamu commented on app/controllers/sessions_controller.rb
> +end
各所で、最終行の最後に改行がないですね 👀 
エディター側で設定するなどしておくのが良さそうです！

[なぜ最終行に改行が必要なのか - komagataのブログ](http://docs.komagata.org/5460)

2018-10-18 07:46 UTC, pokotyamu commented on app/views/layouts/_header.html.erb
> +</header>
29~32 行目の閉じタグって必要ですか？ 👀

2018-10-18 07:46 UTC, pokotyamu commented on config/routes.rb
> +  get 'users/new'
13 行目にある `resources :users` という定義とかぶってないですか？ 👀

2018-10-18 07:46 UTC, pokotyamu commented on app/models/user.rb
> +  enum gender: {"":0, Male: 1, Female: 2 }
うーん 🤔 
もし Male/Female 以外ならば、 Other などはどうでしょうか？

また、あくまで Ruby コードの世界なので、 Hash キーは小文字のみが一般的です！

2018-10-18 07:46 UTC, pokotyamu commented on app/models/user.rb
> +                    uniqueness: { case_sensitive: false }
email のバリデーションいいですね 👍 

すごく細かいですが、 `{}` は最初と最後に空白を入れておくのが一般的です！
`format: { with: VALID_EMAIL_REGEX }`

2018-10-18 07:46 UTC, pokotyamu commented on app/models/user.rb
> +                    uniqueness: { case_sensitive: false }
ココらへんが統一的な形になっているとより読みやすさが増すと思います！

2018-10-18 14:59 UTC, YYuanqi commented on app/controllers/sessions_controller.rb
> +end
恥ずかしいですが、最終行に改行の重要性は全く知りませんでした。
勉強になりました！

2018-10-18 15:40 UTC, YYuanqi commented on Gemfile
> +  gem 'sqlite3', '1.3.13'
SQLiteの方がPostgreSQLよりローカルでのインストールや設定が楽なので、
今回はdevelopmentにおいてSQLiteを使うことにしました。

しかし、Herokuにデプロイした時に、SQLiteがHerokuにサポートされないことを気付いて、
本番のDBをProstgreSQLにしました。(種類を分ける理由が他にありません．．．)

ちなみに、SQLiteがサポートされない理由は以下のようです。
- [SQLite on Heroku](https://devcenter.heroku.com/articles/sqlite3)

2018-10-18 16:25 UTC, YYuanqi commented on app/models/user.rb
> +  enum gender: {"":0, Male: 1, Female: 2 }
>もし Male/Female 以外ならば、 Other などはどうでしょうか？

確かに、空欄という選択肢よりOther方が適切ですかね。

>また、あくまで Ruby コードの世界なので、 Hash キーは小文字のみが一般的です！

気づいていませんでした。Rubyコーディング規約を後編で用いていきます。

2018-10-18 16:26 UTC, YYuanqi commented on app/views/layouts/_header.html.erb
> +</header>
記入のミスでした。

2018-10-21 13:10 UTC, YYuanqi commented on config/routes.rb
> +  get 'users/new'
@pokotyamu ご指摘の通りです。get 'users/new'がresources :usersに含まれていますので、修正します。

2018-10-21 14:51 UTC, YYuanqi commented on app/models/user.rb
> +                    uniqueness: { case_sensitive: false }
@pokotyamu よく見つけてくれました、さすがプロです！
読みやすさがチーム開発においても大事なことですね。これから重視していきたいです。

2018-10-23 06:24 UTC, pokotyamu commented on Gemfile
> +  gem 'sqlite3', '1.3.13'
> SQLiteの方がPostgreSQLよりローカルでのインストールや設定が楽

そうなんですよね 😓 
おっしゃる通りなんですが、 SQLite だけでしか起こらないエラーなどもある(逆もしかり)ので、基本的に使用する DB は統一してほしいです。
頑張ってローカルの環境でも postgres をインストールしてみてもらえませんか？ 🙏

2018-10-23 06:25 UTC, pokotyamu commented on app/models/user.rb
> +  enum gender: {"":0, Male: 1, Female: 2 }
> 確かに、空欄という選択肢よりOther方が適切ですかね。
> 気づいていませんでした。Rubyコーディング規約を後編で用いていきます。

できれば、この時点で修正してほしいです！

2018-10-23 06:27 UTC, pokotyamu commented
ここからここから、今回の差分のファイルをまとめて全部見ていただいて、ファイルの最後に改行が入ってないファイルが全部大丈夫かを確認してもらってもいいですか？ 👀 
見た感じ結構修正漏れがありそうです。

<img width="854" alt="_by_yyuanqi_ _pull_request__1_ _yyuanqi_e-navigator" src="https://user-images.githubusercontent.com/3479317/47340040-003bd000-d6d8-11e8-9417-906a455ff3d9.png">

2018-10-23 06:34 UTC, pokotyamu reviewed
修正して欲しい点

- プルリクエストのタイトル(https://github.com/YYuanqi/e-navigator/pull/1#issuecomment-430908818)
- Hash キーの小文字(https://github.com/YYuanqi/e-navigator/pull/1#discussion_r226196326)
- 改行忘れ(https://github.com/YYuanqi/e-navigator/pull/1#issuecomment-432110459)
- 閉じタグ消し忘れ(https://github.com/YYuanqi/e-navigator/pull/1#discussion_r227240662)
- ルーティングの修正(https://github.com/YYuanqi/e-navigator/pull/1#discussion_r226862451)

2018-10-23 06:34 UTC, pokotyamu commented on app/views/layouts/_header.html.erb
> +  </div>
差分の修正漏れかな？ 🤔 
この閉じタグは不要だと思います！

2018-10-23 06:35 UTC, pokotyamu commented
修正する際はぜひ、コミットメッセージの書き方も気をつけてみてください！

2018-10-23 13:53 UTC, YYuanqi commented on Gemfile
> +  gem 'sqlite3', '1.3.13'
> 頑張ってローカルの環境でも postgres をインストールしてみてもらえませんか？

了解しました！

2018-10-25 04:02 UTC, pokotyamu commented
https://github.com/YYuanqi/e-navigator/pull/1/commits/539961040b50c8aee962c6c2492ade8a967f8c30
うーん 🤔 
複数の修正内容を一気にやるのは良くないですね。
ファイル単位でコミットを分けるのではなく、修正単位でコミットを分けるようにするほうが良いです！

2018-10-25 04:06 UTC, pokotyamu approved these changes
動作的には良さそうなので、改行の修正だけやって、マージして大丈夫です 👌

2018-10-25 04:06 UTC, pokotyamu commented on app/views/layouts/application.html.erb
> +</html>
惜しいまだ、改行の修正漏れが残ってますよ 👮 

エディターで、ファイルの最後の改行を削除する設定を追加していますか？ 🤔

2018-10-25 14:19 UTC, YYuanqi commented on app/views/layouts/application.html.erb
> +</html>
多分、僕が手動で削除したりしましたので…
今後は残すようにします。

2018-10-25 14:20 UTC, merged