自分の面談日程の表示・登録・編集・削除機能
YYuanqi/e-navigator pull request #2
Opened 2018-11-06 13:18 UTC by YYuanqi

#### やりたかったこと
- 面接日程を表示・登録できる機能の実装
- 面接日程を編集・削除できる機能の実装

#### やったこと
- 面接日程のCRUD操作(登録・表示・編集・削除)
- 面接時間を日本時間に設定

#### 動作確認方法
以下のステップで動作確認を行ってください。
1. ホームページにアクセスする。
2. 右上の"ログイン"ボタンを押下し、ログイン画面に遷移する。
3. 前編で作成したアカウントを使って、e-Navigatorにログインする。
4. ログイン後、 右上の"Account"プールダウンボタンを押下し、"My interviews"を選択し、自分の面接一覧画面にアクセスする。(面接一覧が空になっていることを確認)
5. 「新規面接作成」ボタンを押下し、新規面接作成画面に遷移する。
6. 日付と時間を選択し、「登録」ボタンを押下する。
7. 面接一覧画面にステップ6で登録した面接が正しく表示されることを確認する。
8.  登録した面接の「編集」ボタンを押下し、面接更新画面に遷移する。
9. 日付と時間を変更し、「登録」ボタンを押下する。
10. 面接一覧画面にステップ9で変更した内容が正しく表示されることを確認する。
11. 編集した面接の「削除」ボタンを押下し、削除確認ダイアログボックスで確認ボタンを選択する。
12. 面接一覧が空になったことを確認する。

2018-11-07 08:31 UTC, pokotyamu commented
コミット粒度について。

一つのコミットで複数の作業をやっていませんか？ 🤔 
面接の編集・削除は「面接の編集」「面接の削除」で内容的には別々にすることができますよね？
ここを一緒にしちゃうと、コミットで管理している意味があまりないかと。
後の CSS の調整とアプリケーションのロジックを同時にいじっているのもイマイチですね 😓 

コミット数が増えることは悪いことではないと思うので、一つのやりたいことが終了したらコミットするというのを意識してみてください！

2018-11-07 08:33 UTC, pokotyamu commented
branch 名のことでちょっと前回の提案を謝らないといけない点が...

基本的に branch 名は英語で表記するのが一般的だと思います 🙏 
次回から気をつけてください。

2018-11-07 08:54 UTC, pokotyamu requested changes
いろいろコメント付けました 🙏 
コミット粒度に気をつけつつ修正してみてください！

2018-11-07 08:54 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +#    @interview.update_attributes(status:"保留")
不要なコメントは消しちゃいましょう 👍

2018-11-07 08:54 UTC, pokotyamu commented on app/models/interview.rb
> +  validates :status, presence: true
status も gender のように、 enum で定義してみたらいかがでしょうか？ 😄

2018-11-07 08:54 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    if @interview.update_attributes(status:"保留") && @interview.save
create 時に事前の値の更新的なのを Controller でやるのは微妙な感じです。
この API を通さないとデフォルト値が設定できないというので、 Interview モデルに `before_create` もしくは、 default の値として入れておくのが無難可と思います。

2018-11-07 08:54 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @user = User.find(current_user.id)
ここで再度 User.find で SQL を発行しているのはいらないんじゃないかなと思います。
`@user = current_user` で済みそう 👀 

あとここでインスタンス変数 `@user` に入れたいのってなんでなんですっけ？ 🤔

2018-11-07 08:54 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find(params[:id])
`@interview = current_user.interviews.find(params[:id])`

が複数箇所で出てきてますね。

```
def set_interview
  @interview = Interview.find(params[:id])
end
```

のようなコールバック関数にまとめてしまうのが良さそうに思います！

2018-11-07 08:54 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find(params[:id])
わざわざ、 `current_user.interviews` としなくて、 `Interview` から直接 `#find` してしまえばいいのでは？という話です。

2018-11-07 08:54 UTC, pokotyamu commented on app/models/user.rb
> +  has_many :interviews
User が削除されたタイミングで、それに紐づく Interview が消えるようにして欲しいです 👀

2018-11-10 07:01 UTC, YYuanqi commented on app/controllers/interviews_controller.rb
> +    @user = User.find(current_user.id)
viewでもcurrent_userが直接使えることは知らなかったので、@userに代入しました。

2018-11-10 09:37 UTC, YYuanqi commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find(params[:id])
確かに、IDはユニークなんですね。

2018-11-10 16:10 UTC, YYuanqi commented on app/models/interview.rb
> +  validates :status, presence: true
第二章で定義しようと思ったが、最初の段階で定義したほうがいいですかね。

2018-11-10 16:16 UTC, YYuanqi commented on app/controllers/interviews_controller.rb
> +    if @interview.update_attributes(status:"保留") && @interview.save
自分も作った時に違和感を感じしました。
default値に入れます。

2018-11-10 16:29 UTC, YYuanqi commented
> コミット粒度について。
> 
> 一つのコミットで複数の作業をやっていませんか？ 🤔
> 面接の編集・削除は「面接の編集」「面接の削除」で内容的には別々にすることができますよね？
> ここを一緒にしちゃうと、コミットで管理している意味があまりないかと。
> 後の CSS の調整とアプリケーションのロジックを同時にいじっているのもイマイチですね 😓
> 
ついにコミットを忘れてしまいました。ソースを管理する意識が低いのは原因だと思っています。

> コミット数が増えることは悪いことではないと思うので、一つのやりたいことが終了したらコミットするというのを意識してみてください！

確かにコミットの数を抑えたいと思いました。😓
コミットの粒度を見直します！

2018-11-13 01:45 UTC, pokotyamu commented
コミットメッセージについて
---

> ついにコミットを忘れてしまいました。ソースを管理する意識が低いのは原因だと思っています。

経験を積めば、やりたいことリストを先に作ってそれに沿って実装をするというやり方もできるようになるので、今は実装したあとにどの粒度で分けれたか？を考えるでも良いと思いますよ！
何事も練習だと思います 😄 


コミットメッセージに `@` をつけるときは、 `` ←これで囲んでハイライトさせるようにしましょう！
今回で言えば `@user` さんにメンションが飛んでしまうので 🙏

2018-11-13 01:56 UTC, pokotyamu requested changes
レビューしました！
コミット粒度良くなったと思います 😄 
適宜修正よろしくお願いします！

2018-11-13 01:56 UTC, pokotyamu commented on app/models/interview.rb
> +  validates :status, presence: true
カラム定義は、なるべく変えないほうが良いと思いますよ！
なので最初からその予定があるならば、そうした方が良いと思います！

2018-11-13 01:56 UTC, pokotyamu commented on app/models/interview.rb
> +  validates :status, presence: true
特に今回で言えば、 String 型から Integer 型へ変更になるので、そこの移行とかも考えなきゃいけなくなりますしね 🙏

2018-11-13 01:56 UTC, pokotyamu commented on app/models/interview.rb
> +  enum status: { 保留: 0, 承認: 1, 却下: 2 }
enum のキー定義に日本語はあまり良くないですね 👀 
Ruby では日本語のキーにも対応していますが、英語で定義した後に辞書で翻訳みたいなのが普通ですね。

2018-11-13 01:56 UTC, pokotyamu commented on app/models/interview.rb
> +  enum status: { 保留: 0, 承認: 1, 却下: 2 }
最悪翻訳はしなくてもいいので、キーの日本語部分だけでも対応よろしくお願いします 🙏

2018-11-13 14:37 UTC, YYuanqi commented on app/models/interview.rb
> +  enum status: { 保留: 0, 承認: 1, 却下: 2 }
カラム定義について承知しました！

翻訳の件についてネットの情報を参考して対応してみました。
言語の対応もなかなか大変ですね。。

2018-11-15 01:25 UTC, pokotyamu commented on app/models/interview.rb
> +  enum status: { 保留: 0, 承認: 1, 却下: 2 }
翻訳までしてくれたんですね 😄 
いい感じにできていると思いますよ 👌

2018-11-15 01:28 UTC, pokotyamu approved these changes
動作的にも問題なさそうなので良いと思いました 👌 
末尾改行だけよろしくおねがいします！

VS Code なら: https://qiita.com/norikt/items/83674fadd79a88bf7824
`エディタ名 末尾改行` とかで調べると保存時に勝手に追加してくれるやり方が載っているかもです！
あと、不要な空白を削除しておくと幸せになれそう。

2018-11-15 01:28 UTC, pokotyamu commented on config/locales/ja.yml
> +    pm: "午後"
ファイル末尾改行 👮

2018-11-15 01:30 UTC, pokotyamu commented on config/locales/ja.yml
> +
ここも末尾改行なかった。
そして不要な空行も消しましょう！

2018-11-17 14:49 UTC, merged