面接官が面談日程を承認 or 拒否するための機能
YYuanqi/e-navigator pull request #3
Opened 2018-11-20 13:56 UTC by YYuanqi

第二章を完成しましたので、レビューをお願い致します。

**[Heroku](https://e-navigator-yyuanqi.herokuapp.com/)**
---
#### やりたかったこと
- ユーザーの一覧ページの実装
- 面接官用の面接一覧ページの実装
- 面談日程を承認/却下する機能の実装

#### やったこと
-  上記の機能の実装

#### 動作確認方法

以下のステップで動作確認を行ってください。
1. ホームページにアクセスし、新しいユーザを登録する。
2. 新規登録したユーザを使用し、複数の面接日程を登録する。その後、ログアウトする。
3. ホームページから前編で作成したユーザでログインする。
4. 右上の"Users"ボタンを押下し、ユーザー一覧画面に遷移する。
5. ステップ1で登録したユーザの情報が表示されることを確認する。
6. 「面接一覧」ボタンを押下し、面接官用の面接日程一覧ページに遷移する。
7.  表示される面接日程の中で、任意の一つの日程を選択し、面接が予約されることを確認する。
8.  右上の"Users"ボタンを押下し、「面接日時」欄に ステップ7で選択した日程が表示されることを確認する。
9. またステップ1で作成したユーザーでログインし、自分の面接一覧画面に遷移する。
10. ステップ8で予約された面接日程の状態が「承認」、その他が「却下」になっていることを確認。

#### 何か分からない点や、ここ頑張りましたなどあればこちらに書いてください。

今回、面接官が行う承認処理を`InterviewsController#show`で実装しましたが、railsの規約に違反していないかが気になります。データ更新系の処理は基本`InterviewsController#update`中に実装すべきでしょうか？

2018-11-21 03:36 UTC, pokotyamu commented
👀

2018-11-21 03:38 UTC, pokotyamu commented
> 今回、面接官が行う承認処理をInterviewsController#showで実装しましたが、railsの規約に違反していないかが気になります。データ更新系の処理は基本InterviewsController#update中に実装すべきでしょうか？

うーん、仰る通り `#show` のアクションにたいしては GET の HTTP メソッドでアクセスすることになります。
その時に更新(PUT, PATCH 系)のアクションが行われるのは良くないと思います。

また、 update は面接を作ったユーザー本人が更新する時に使いたい気がするので、新しいアクションとして `apply` を用意するのはどうでしょうか？
一覧の画面から `InterviewsController#apply` を呼ぶようなイメージです！

2018-11-21 03:50 UTC, pokotyamu requested changes
list と index を分けて実装していた意図が分からなかったです 🙏 
index に `#apply` アクションへのリンクを用意して、そこの中で実行する形がいいかと思うので検討してみてください！

2018-11-21 03:50 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> -  <%= link_to "新規面接作成", new_user_interview_path(:user), class: "btn btn-default btn-primary" %>
User 一覧を作るコミットで面接一覧のページを削除している？ 💭

2018-11-21 03:50 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +  <%= link_to "新規面接作成", new_user_interview_path(:user), class: "btn btn-default btn-primary" %>
ここも `add users list page` となっていますが、やってる内容的には、面接一覧を作ってますね 👀

2018-11-21 03:50 UTC, pokotyamu commented on app/views/interviews/list.html.erb
> +<% end %>
`list` かぁ 🤔 
ここアクションの `index` と分けたのって何か意図がありますか？

2018-11-21 03:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interviews = User.find(params[:user_id]).interviews.where.not(status: 1)
`status: :1` って指定もできますが、せっかく enum を使ってますし、 `status: :approved ` とかって指定するとわかりやすさが増しますよ！

2018-11-21 03:50 UTC, pokotyamu commented on app/views/users/index.html.erb
> +        <% if user.interviews.find_by(status: 1) %>
ここ、 controller 側から検索結果を教えてあげたら２回 SQL を実行しなくて済みそうですね！

2018-11-21 03:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interviews = User.find(params[:user_id]).interviews.where.not(status: 1)
b96394f

で治ってた 🙏

2018-11-21 13:05 UTC, YYuanqi commented on app/views/interviews/index.html.erb
> -  <%= link_to "新規面接作成", new_user_interview_path(:user), class: "btn btn-default btn-primary" %>
誤って`index.html.erb`の内容をクリアされた状態でコミットしました。

2018-11-21 13:21 UTC, YYuanqi commented on app/views/interviews/index.html.erb
> +  <%= link_to "新規面接作成", new_user_interview_path(:user), class: "btn btn-default btn-primary" %>
ここは前回のミスを挽回するために、慌てて内容を戻してコミットしました。
最初のコミットをする前に、編集した内容を確認すべきでした。

2018-11-21 13:46 UTC, YYuanqi commented on app/views/interviews/list.html.erb
> +<% end %>
面接官ための面接一覧を自分の面接一覧を同じビューファイルでの実装は、ビューで制御するところが多いと思いました。(共通化できる部分が少ないと感じたので、２つのビューに分けました。)
今思えば、部分テンプレートを使って`index`アクションと一致したほうがメンテナンスしやすいですね。
修正します!

2018-11-26 16:21 UTC, YYuanqi commented on app/views/users/index.html.erb
> +        <% if user.interviews.find_by(status: 1) %>
ご指摘の通りです。
修正してみました。

2018-11-28 09:32 UTC, pokotyamu requested changes
大まかな修正としては良さそうに思いました！
`InterviewsController#index` の実装だけちょっと気になったので、確認よろしくおねがいします 🙏

2018-11-28 09:32 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    end
この分岐は表示側の問題なきがするので、

`@interviews = @user.interview.all`

だけにして view 側で `approved` ならそれに合わせた表示に切り替えるというのはどうでしょう？

2018-11-28 09:32 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    unless current_user == @user
`unless current_user == @user` とするなら `if current_user != @user` と書くかなぁ。
極力 `if` 文で書ける内容は `if` の方が読みやすいと思います

2018-11-28 09:32 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> -  <%= link_to "新規面接作成", new_user_interview_path(:user), class: "btn btn-default btn-primary" %>
コミットメッセージや、コミット内容を修正することも可能なので、次同じ事態に遭遇した時は調べてみるといいと思います！

2018-11-28 09:32 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @interview.save
ここ `@interview.approved!` とすることもできますよ〜！
２行を１行に短縮！

2018-11-28 15:10 UTC, YYuanqi commented on app/controllers/interviews_controller.rb
> +    end
なるほど！コントローラ側がデータを渡すだけになり、もともとのviewに依存している感じがなくなりますね。

2018-11-28 15:12 UTC, YYuanqi commented on app/controllers/interviews_controller.rb
> +    unless current_user == @user
ここが迷いました。今後は`if`文を優先で使用します。

2018-11-28 15:36 UTC, YYuanqi commented on app/controllers/interviews_controller.rb
> +      @interview.save
勉強になりました！

2018-11-30 08:18 UTC, pokotyamu approved these changes
良さそう 👍 
LGTM です 👌

2018-11-30 08:19 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    end
ここ直接のフィードバックの時にもう少し説明しますね！
View に実装すべきか、 Controller に実装すべきか。

2018-12-01 04:06 UTC, merged