面談日程を知らせるためのメール送信機能
YYuanqi/e-navigator pull request #4
Opened 2018-12-04 13:30 UTC by YYuanqi

@pokotyamu さん

第三章が完成しました。
また、レビューをお願い致します。:pray:

**[Heroku](https://e-navigator-yyuanqi.herokuapp.com/)**
---
#### やりたかったこと
- メール送信機能の実装
  1. ユーザーを指定して申請をすると、指定したユーザーに面談日程承認の承認依頼を送信する
  2. 承認が押された際に、両者に面接日が決ったことを送信する

#### やったこと
- 開発環境と本番環境でAction Mailerを設定し、上記の機能を実装

#### 動作確認方法
1. ユーザー(申請者)を新規で作成する。
2. 右上の「Account」プルダウンボタンから「My interviews」をクリックする。
3. 面接日程を複数作成する。
4. 「ユーザを指定」から面接官(前編で作成したアカウント)を選択し、申請ボタンを押下する。
5.  承認依頼のメールが選択したメールアドレスに届いていることを確認する。また、メールの内容に、申請者の名前が正しく入っていることを確認する。
6. ログアウトして、前編で作成した面接官でログインする。
7. 右上の「Users」ボタンを押下し、申請者の面接一覧を表示する。
8. 面接日程をクリックして、承認する。
9. 申請者と面接官宛に面接日の通知メールが届いていることを確認する。また、メールの内容にクリックした面接日程が正しく表示されているを確認する。

#### その他

2018-12-05 07:15 UTC, pokotyamu requested changes
Mailer の名前つけについて修正よろしくおねがいします 🙏

2018-12-05 07:15 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +class NotificationMailer < ApplicationMailer
`NotificationMailer` か 👀 
これだとありとあらゆるメール通知がこの中に入ってこないですか？ 👀 
例えば、ユーザーのメールを作るとなってもここに来ますし、アプリの更新をメール通知したいみたいなときもここに実装することになりますよね。

これらを避けるために `InterviewMailer` などでメールに関するメソッドを管理するのはどうでしょうか？

2018-12-05 07:15 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +  def send_comfirmation_to_users(to_user, from_user, time)
`Controller` のアクションと揃える意味で `#apply` でも良さそう

2018-12-05 07:15 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +  def send_request_to_user(to_user, from_user)
`request` が使えないからしょうがないんだよなぁ 🤔 
自分だったら `approve` とかで `Controller` のメソッドごと直すと思います。

2018-12-05 07:15 UTC, pokotyamu commented on app/mailers/notification_mailer.rb
> +  def send_request_to_user(to_user, from_user)
`to_user` や `from_user` はイマイチ分かりにくいので、 `interviewer`, `interviewee` のようにどんなユーザーかの表現があると良いと思いました 👍

2018-12-05 07:15 UTC, pokotyamu commented on Gemfile
> +  gem 'letter_opener_web'
development グループに追加しているの良いですね 👍

2018-12-05 07:15 UTC, pokotyamu commented on app/views/notification_mailer/send_comfirmation_to_users.html.erb
> +<p><%=@to_user.name %> さんの面接時間が <%= @from_user.name %> さんによって、以下の内容で、承認されました。</p>
ここも `interviewer` `interviewee` の方が、実装の意図が伝わりやすくていいと思います！

2018-12-05 07:15 UTC, pokotyamu commented on config/environments/production.rb
> +    :password       => ENV['GMAIL_PASSWORD'],
うん！しっかり環境変数にパスワード関係を設定できてますね 👍

2018-12-05 13:04 UTC, YYuanqi commented on app/mailers/notification_mailer.rb
> +class NotificationMailer < ApplicationMailer
仰る通りです。
名前を付ける時に、ほかの状況を考慮していませんでした。:pensive:
修正します！

2018-12-05 13:07 UTC, YYuanqi commented on Gemfile
> +  gem 'letter_opener_web'
:grin:

2018-12-05 13:08 UTC, YYuanqi commented on app/views/notification_mailer/send_comfirmation_to_users.html.erb
> +<p><%=@to_user.name %> さんの面接時間が <%= @from_user.name %> さんによって、以下の内容で、承認されました。</p>
:grin:

2018-12-05 14:07 UTC, YYuanqi commented on app/mailers/notification_mailer.rb
> +  def send_request_to_user(to_user, from_user)
確かにわかりやすさが欠如していると思います。
名前をいろいろ修正します。(アイデアを盗ませてください😏)

2018-12-05 14:47 UTC, YYuanqi commented on app/mailers/notification_mailer.rb
> +  def send_comfirmation_to_users(to_user, from_user, time)
こういう手もありますね！:thumbsup:

2018-12-10 03:23 UTC, pokotyamu commented
大変遅くなってしまって、すみませんでした 🙇

2018-12-10 03:23 UTC, pokotyamu commented
いい感じに分かりやすくなってますね 👍 
あえて言えば、コミットの粒度として `InterviewMailer への名称変更`、 `apply` の実装、 `approve` の実装といった感じで分けるとより良かったかと思います！

2018-12-10 03:26 UTC, pokotyamu commented
動作的にも大丈夫そうですね！
マージして問題ないと思います 😄

2018-12-10 03:26 UTC, pokotyamu approved these changes
完走お疲れ様でした！

2018-12-10 05:29 UTC, merged